from typing import Optional
from datetime import datetime
from .base import OntologyObjectBase


ALERT_SEVERITIES = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}
ALERT_TYPES = {
    "CIRP_ACTIVE", "OFFSHORE_DIRECTOR", "DISQUALIFIED_DIRECTOR",
    "ONGOING_REGULATORY", "PROJECT_DELAY", "ADDRESS_CLUSTERING",
    "UNAPPROVED_RPT", "REGULATORY_RECIDIVISM", "DIRECTOR_PROLIFERATION",
    "CIRP_CONTAGION", "FILING_COMPLIANCE",
}


class Alert(OntologyObjectBase):
    alertId: str
    severity: str
    alertType: str
    title: str
    message: str
    affectedEntityType: Optional[str] = None
    affectedEntityId: Optional[str] = None
    createdAt: Optional[datetime] = None
    resolvedAt: Optional[datetime] = None
    resolvedBy: Optional[str] = None
    isActive: bool = True
    lastUpdated: Optional[datetime] = None

    def primary_key_value(self) -> str:
        return self.alertId

    def compute_data_quality_score(self) -> float:
        critical = ["alertId", "severity", "alertType", "title", "message"]
        present = sum(1 for f in critical if getattr(self, f, None) is not None)
        return round((present / len(critical)) * 100, 2)

    class OntologyMeta:
        api_name = "alert"
        display_name = "Alert"
        plural_name = "Alerts"
        description = "An intelligence alert generated by anomaly detection"
        primary_key_field = "alertId"
        critical_properties = ["alertId", "severity", "alertType", "title", "isActive"]


ALERT_DEFINITION = {
    "api_name": "alert",
    "display_name": "Alert",
    "plural_name": "Alerts",
    "description": "An intelligence alert generated by anomaly detection",
    "primary_key_field": "alertId",
    "properties": [
        {"name": "alertId", "type": "str", "required": True, "immutable": True},
        {"name": "severity", "type": "str", "required": True},
        {"name": "alertType", "type": "str", "required": True},
        {"name": "title", "type": "str", "required": True},
        {"name": "message", "type": "str", "required": True},
        {"name": "affectedEntityType", "type": "str"},
        {"name": "affectedEntityId", "type": "str"},
        {"name": "createdAt", "type": "datetime"},
        {"name": "resolvedAt", "type": "datetime"},
        {"name": "resolvedBy", "type": "str"},
        {"name": "isActive", "type": "bool"},
    ],
    "interfaces": ["TemporalEntity"],
}
