const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('typescript')
const Module = require('node:module')
const source = fs.readFileSync(path.join(__dirname, '../src/components/graph/investigation.ts'), 'utf8')
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText
const helper = new Module(__filename)
helper._compile(compiled, __filename)
const { shortestPath, sharedConnections, evidenceIds } = helper.exports
const nodes = ['c1', 'c2', 'd1', 'a1', 'isolated'].map(id => ({ data: { id } }))
const edge = (id, source, target, linkType, isInferred = false) => ({ data: { id, source, target, linkType, isInferred } })
const edges = [edge('d1c1', 'd1', 'c1', 'DIRECTED'), edge('d1c2', 'd1', 'c2', 'DIRECTED'), edge('c1a1', 'c1', 'a1', 'REGISTERED_AT'), edge('c2a1', 'c2', 'a1', 'REGISTERED_AT')]
assert.equal(shortestPath(nodes, edges, 'c1', 'c2').edges.length, 2)
assert.deepEqual(shortestPath(nodes, edges, 'c1', 'c1'), { nodes: ['c1'], edges: [] })
assert.equal(shortestPath(nodes, edges, 'c1', 'isolated'), null)
assert.equal(shortestPath(nodes, edges, 'missing', 'c1'), null)
assert.equal(shortestPath(nodes, [], 'c1', 'c2'), null)
assert.deepEqual(shortestPath(nodes, edges, 'c1', 'c2'), shortestPath(nodes, [...edges].reverse(), 'c1', 'c2'))
assert.deepEqual(sharedConnections(edges, 'c1', 'c2'), { directors: ['d1'], addresses: ['a1'] })
assert.deepEqual(sharedConnections(edges.filter(e => e.data.linkType !== 'DIRECTED'), 'c1', 'c2'), { directors: [], addresses: ['a1'] })
assert.deepEqual(sharedConnections(edges.map(e => ({ data: { ...e.data, isInferred: true } })), 'c1', 'c2'), { directors: [], addresses: [] })
assert.deepEqual(evidenceIds('R1, R2,R1'), ['R1', 'R2'])
assert.deepEqual(evidenceIds(['R1', null, ' R2 ']), ['R1', 'R2'])
assert.deepEqual(evidenceIds(undefined), [])
console.log('12 investigation assertions passed')
